service: generation-bot-dev
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: us-east-2
  lambdaHashingVersion: '20201221'
  iam:
    role:
      managedPolicies:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AWSLambda_FullAccess'

functions:
  gen-bot-api-create:
    name: dev-gen-bot
    handler: index.endpoint
    events:
      - http:
          path: api/generate
          method: post
          cors: true
          private: false

